AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a certificate for CloudFront to validate the domain ownership

Parameters:
  DomainName:
    Type: String

Resources:
  AcmCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          ValidationDomain: !Ref DomainName

Outputs:
  AcmCertificateArn:
    Value: !Ref AcmCertificate
